### ISSUE TITLE
debloat readme: remove 30 MB demo video

### ISSUE THREAD

**Issue by milahu** [Wenzel/pyvmidbg#49]
on my metered connection, that video costs 4 cents to download ..
please stop robbing my cents, and only show the video on demand

maybe use mp4 format, since gif is not seekable

**Comment by Wenzel** [comment]
hi @milahu ,
thanks for reporting this legitimate issue.

I will remove the demo and leave the link instead.

**Comment by milahu** [comment]
thanks : )

also ..

> libvmi: support is ongoing, see kvm-vmi/libvmi (branch kvmi)

looks like the kvmi-branch was merged?

i tried to follow the setup guide at
https://kvm-vmi.github.io/kvm-vmi/kvmi/setup.html

what i found is, i need a custom kernel
with REMOTE_MAPPING and KVM_INTROSPECTION
( /proc/config.gz says no )

i only read "pyvmidbg: supported"
so i thought "hey! that route looks easier than setting-up xen"
but now it seems, the xen-route is easier .... i will see

oh, and a typo

> 2017: BitDefender published a set VMI patches on the mailing list

.. a set **of** VMI patches ..

**Comment by Wenzel** [comment]
> looks like the kvmi-branch was merged?

Yep, you are absolutely correct.
The thing is that I haven't been maintaining this tool as much as I wanted to.
What I wanted was to build a community around it and see more people using it and contribute, so it would be sustainable in the long run.
But that demands a lot of time at home that I don't really have, also considering how many open-source projects I'm involved in.
(KVM-VMI is part of these, and I'm happy that all of these changes are now available upstream :) )

But I should now update the setup info for pyvmidbg, now that the situation has changed on the KVM-VMI repo.


> what i found is, i need a custom kernel

indeed, KVM is so deeply tied to the linux kernel that you can't just compile it as an external module, but you need to rebuild an entire kernel (and activate some options too for VMI)

> i only read "pyvmidbg: supported"
> so i thought "hey! that route looks easier than setting-up xen"

It's true for KVM, but needs a bit of setup.
On the Xen side, the introspection APIs are available right away when you install Xen, so I'd say it's easier.
I was maintaining a Vagrant configuration to setup pyvmidbg in Xen, if that helps:
https://github.com/Wenzel/vagrant-xen-pyvmidbg

> oh, and a typo

thanks
Feel free to open an issue if you have another error in the setup.

cheers !
